#define LED_PIN GPIOv_from_PORT_PIN(GPIO_port_B, 11)
//#define SW1_PIN GPIOv_from_PORT_PIN(GPIO_port_D, 0)
//#define SW2_PIN GPIOv_from_PORT_PIN(GPIO_port_D, 4)
//#define SW3_PIN GPIOv_from_PORT_PIN(GPIO_port_C, 0)
//#define ADC_PIN GPIOv_from_PORT_PIN(GPIO_port_D, 3)
//#define SPK_PIN GPIOv_from_PORT_PIN(GPIO_port_D, 2)
//#define LED_PIN GPIOv_from_PORT_PIN(GPIO_port_D, 5)
//#define UART_PIN GPIOv_from_PORT_PIN(GPIO_port_D, 6)
#define SW1_PIN GPIOv_from_PORT_PIN(GPIO_port_B, 3)
#define SW2_PIN GPIOv_from_PORT_PIN(GPIO_port_B, 4)
#define SW3_PIN GPIOv_from_PORT_PIN(GPIO_port_B, 5)

